import type { KBArticle, KBCategory } from "./types";

export const kbCategories: KBCategory[] = [
  { id: "kb-cat-1", name: "Shipping & Delivery", description: "Policies and info about shipping", articleCount: 3 },
  { id: "kb-cat-2", name: "Returns & Refunds", description: "Return and refund policies", articleCount: 2 },
  { id: "kb-cat-3", name: "Product Guides", description: "How-to guides and product info", articleCount: 3 },
  { id: "kb-cat-4", name: "Store Policies", description: "General store policies and terms", articleCount: 2 },
  { id: "kb-cat-5", name: "Account & Orders", description: "Account management and order help", articleCount: 2 },
  { id: "kb-cat-6", name: "FAQs", description: "Frequently asked questions", articleCount: 3 },
];

export const mockArticles: KBArticle[] = [
  {
    id: "kb-1",
    title: "Shipping Policy",
    content: "We offer free standard shipping on all orders over $50. Standard delivery takes 3-5 business days. Express shipping (1-2 business days) is available for $12.99. International shipping is available to over 50 countries with delivery in 7-14 business days.",
    contentType: "article",
    category: "Shipping & Delivery",
    tags: ["shipping", "delivery", "free-shipping"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-25T14:00:00Z",
  },
  {
    id: "kb-2",
    title: "How to Track Your Order",
    content: "Once your order ships, you will receive an email with a tracking number. You can also track your order by logging into your account and visiting the Orders page. Tracking information typically updates within 24 hours of shipment.",
    contentType: "article",
    category: "Shipping & Delivery",
    tags: ["tracking", "orders", "shipping"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    createdAt: "2024-01-11T10:00:00Z",
    updatedAt: "2024-01-26T11:00:00Z",
  },
  {
    id: "kb-3",
    title: "International Shipping Information",
    content: "We ship to over 50 countries worldwide. International orders may be subject to customs duties and taxes imposed by the destination country. These fees are the responsibility of the recipient. Delivery times vary by destination.",
    contentType: "article",
    category: "Shipping & Delivery",
    tags: ["international", "shipping", "customs"],
    status: "active",
    source: "url",
    sourceUrl: "https://example.com/shipping/international",
    linkedProducts: [],
    createdAt: "2024-01-12T08:00:00Z",
    updatedAt: "2024-01-27T09:00:00Z",
  },
  {
    id: "kb-4",
    title: "Return Policy",
    content: "We accept returns within 30 days of delivery. Items must be unused and in their original packaging. To initiate a return, log into your account and select the order you wish to return. Refunds are processed within 5-7 business days after we receive the returned item.",
    contentType: "article",
    category: "Returns & Refunds",
    tags: ["returns", "refunds", "policy"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    createdAt: "2024-01-08T09:00:00Z",
    updatedAt: "2024-01-24T16:00:00Z",
  },
  {
    id: "kb-5",
    title: "Refund Processing Times",
    content: "Once we receive your returned item, refunds are processed within 5-7 business days. The refund will be issued to your original payment method. Credit card refunds may take an additional 3-5 business days to appear on your statement depending on your bank.",
    contentType: "article",
    category: "Returns & Refunds",
    tags: ["refunds", "processing", "payment"],
    status: "active",
    source: "document",
    sourceFile: "refund-policy.pdf",
    linkedProducts: [],
    createdAt: "2024-01-09T10:00:00Z",
    updatedAt: "2024-01-23T12:00:00Z",
  },
  {
    id: "kb-6",
    title: "Wireless Headphones User Guide",
    content: "To pair your Wireless Noise-Canceling Headphones: 1) Turn on the headphones by holding the power button for 3 seconds. 2) Enable Bluetooth on your device. 3) Select 'Leaf Headphones' from the available devices. The LED will turn solid blue when connected. Battery life is up to 30 hours with ANC on.",
    contentType: "article",
    category: "Product Guides",
    tags: ["headphones", "guide", "pairing", "bluetooth"],
    status: "active",
    source: "product-sync",
    linkedProducts: ["1"],
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-28T10:00:00Z",
  },
  {
    id: "kb-7",
    title: "Smart Watch Setup Guide",
    content: "Getting started with your Smart Watch Pro: 1) Charge the watch fully before first use. 2) Download the Leaf companion app. 3) Pair via Bluetooth. 4) Configure your profile and fitness goals. The watch features heart rate monitoring, GPS tracking, and sleep analysis.",
    contentType: "article",
    category: "Product Guides",
    tags: ["smartwatch", "setup", "guide", "fitness"],
    status: "active",
    source: "product-sync",
    linkedProducts: ["2"],
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-01-29T11:00:00Z",
  },
  {
    id: "kb-8",
    title: "Camera Care Instructions",
    content: "To maintain your 4K Ultra HD Camera: Always use the lens cap when not in use. Clean the lens with a microfiber cloth only. Store in a dry, dust-free environment. Update firmware regularly via the companion app. The camera is not waterproof — avoid exposure to moisture.",
    contentType: "article",
    category: "Product Guides",
    tags: ["camera", "care", "maintenance"],
    status: "draft",
    source: "product-sync",
    linkedProducts: ["3"],
    createdAt: "2024-01-17T10:00:00Z",
    updatedAt: "2024-01-30T09:00:00Z",
  },
  {
    id: "kb-9",
    title: "Terms of Service",
    content: "By using our website and services, you agree to these terms. We reserve the right to modify these terms at any time. Users must be 18 years or older to make purchases. All content on this site is protected by copyright. Unauthorized use is prohibited.",
    contentType: "article",
    category: "Store Policies",
    tags: ["terms", "legal", "policy"],
    status: "active",
    source: "url",
    sourceUrl: "https://example.com/terms",
    linkedProducts: [],
    createdAt: "2024-01-05T08:00:00Z",
    updatedAt: "2024-01-20T14:00:00Z",
  },
  {
    id: "kb-10",
    title: "Privacy Policy",
    content: "We are committed to protecting your privacy. We collect only the information necessary to process your orders and improve your experience. Your data is never sold to third parties. We use encryption to protect sensitive information. You can request data deletion at any time.",
    contentType: "article",
    category: "Store Policies",
    tags: ["privacy", "data", "legal"],
    status: "active",
    source: "url",
    sourceUrl: "https://example.com/privacy",
    linkedProducts: [],
    createdAt: "2024-01-06T09:00:00Z",
    updatedAt: "2024-01-21T15:00:00Z",
  },
  {
    id: "kb-11",
    title: "How to Update Your Account",
    content: "To update your account information: 1) Log into your account. 2) Go to Account Settings. 3) Edit your name, email, password, or shipping addresses. 4) Click Save. Changes to your email will require verification.",
    contentType: "article",
    category: "Account & Orders",
    tags: ["account", "settings", "profile"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    createdAt: "2024-01-13T10:00:00Z",
    updatedAt: "2024-01-27T16:00:00Z",
  },
  {
    id: "kb-12",
    title: "Order Cancellation Policy",
    content: "Orders can be cancelled within 1 hour of placement. After that, the order enters our fulfillment process and cannot be cancelled. If you need to cancel after 1 hour, please wait for delivery and initiate a return instead.",
    contentType: "article",
    category: "Account & Orders",
    tags: ["orders", "cancellation", "policy"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    createdAt: "2024-01-14T11:00:00Z",
    updatedAt: "2024-01-28T12:00:00Z",
  },
  {
    id: "kb-13",
    title: "What payment methods do you accept?",
    content: "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, Apple Pay, Google Pay, and bank transfers for orders over $500.",
    contentType: "faq",
    category: "FAQs",
    tags: ["payment", "faq"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    faqQuestion: "What payment methods do you accept?",
    faqAnswer: "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, Apple Pay, Google Pay, and bank transfers for orders over $500.",
    createdAt: "2024-01-07T09:00:00Z",
    updatedAt: "2024-01-22T10:00:00Z",
  },
  {
    id: "kb-14",
    title: "Do you offer price matching?",
    content: "Yes, we offer price matching on identical items from authorized retailers. Contact our support team with the competitor's link and we will match the price.",
    contentType: "faq",
    category: "FAQs",
    tags: ["pricing", "faq"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    faqQuestion: "Do you offer price matching?",
    faqAnswer: "Yes, we offer price matching on identical items from authorized retailers. Contact our support team with the competitor's link and we will match the price.",
    createdAt: "2024-01-08T10:00:00Z",
    updatedAt: "2024-01-23T11:00:00Z",
  },
  {
    id: "kb-15",
    title: "How do I contact customer support?",
    content: "You can reach our support team via live chat on the website (available 24/7), by email at support@leaf.example.com, or by phone at 1-800-LEAF during business hours (9 AM - 6 PM EST, Monday - Friday).",
    contentType: "faq",
    category: "FAQs",
    tags: ["support", "contact", "faq"],
    status: "active",
    source: "manual",
    linkedProducts: [],
    faqQuestion: "How do I contact customer support?",
    faqAnswer: "You can reach our support team via live chat on the website (available 24/7), by email at support@leaf.example.com, or by phone at 1-800-LEAF during business hours (9 AM - 6 PM EST, Monday - Friday).",
    createdAt: "2024-01-09T11:00:00Z",
    updatedAt: "2024-01-24T12:00:00Z",
  },
];
