"""use_email_as_user_pk

Revision ID: 38013969d66c
Revises: 4efa81fabe5e
Create Date: 2026-06-13 16:30:00.000000

"""
from typing import Sequence, Union
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38013969d66c'
down_revision: Union[str, None] = '4efa81fabe5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    This migration removes the ``username`` column and switches the ``user``
    table to use ``email`` as its primary key. ``group`` and ``item`` use
    auto-incrementing integer primary keys.

    Note: this migration drops and recreates the affected tables, which will
    remove existing data in those tables.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'groupuserlink' in tables:
        op.drop_table('groupuserlink')
    if 'item' in tables:
        op.drop_table('item')
    if 'group' in tables:
        op.drop_table('group')
    if 'user' in tables:
        op.drop_table('user')

    op.create_table('user',
        sa.Column('email', sa.VARCHAR(), nullable=False),
        sa.Column('full_name', sa.VARCHAR(), nullable=True),
        sa.Column('isActive', sa.BOOLEAN(), nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('email')
    )
    op.create_table('group',
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('admin', sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(['admin'], ['user.email'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('is_done', sa.BOOLEAN(), nullable=False),
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.email'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupuserlink',
        sa.Column('group_id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.email'], ),
        sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Restores the previous schema where ``user`` had a UUID ``id`` primary key
    and a unique ``username`` column.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'groupuserlink' in tables:
        op.drop_table('groupuserlink')
    if 'item' in tables:
        op.drop_table('item')
    if 'group' in tables:
        op.drop_table('group')
    if 'user' in tables:
        op.drop_table('user')

    op.create_table('user',
        sa.Column('username', sa.VARCHAR(), nullable=False),
        sa.Column('email', sa.VARCHAR(), nullable=True),
        sa.Column('full_name', sa.VARCHAR(), nullable=True),
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('isActive', sa.BOOLEAN(), nullable=False),
        sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)

    op.create_table('group',
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('admin', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['admin'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
        sa.Column('name', sa.VARCHAR(), nullable=False),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('is_done', sa.BOOLEAN(), nullable=False),
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupuserlink',
        sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###
